### ISSUE TITLE
Joey NMT for paper Correct Me If You Can

### ISSUE THREAD

**Issue by AmanSinghal927** [bricksdont/joeynmt-toy-models#2]
I am trying to replicate the results presented in the paper "Correct Me If You Can". I am using Google Colab. I have already cloned the Joey NMT repo as well as Downloaded the model into the same location. I notice that for the toy models a few shell scripts are present to evaluate the toy models. However, I am unclear how I can evaluate the WMT17 en-de model. Can someone please help?

**Comment by bricksdont** [comment]
Hi, this is not the Joeynmt repository (https://github.com/joeynmt/joeynmt), this is just a repo with example scripts. The scripts are not expected to be useful for a real experiment.

I would recomment that you open an issue in the actual Joey repo. Please make sure you include a link to your Colab, and also explain more clearly what your problem is with evaluation.

**Comment by bricksdont** [comment]
Ah, you already did - closing.
